<?php

use App\Http\Controllers\CallRecordController;
use App\Http\Controllers\AdminAuthController;
use App\Http\Controllers\LeadController;
use App\Http\Controllers\ScheduleEventController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\AiAgentController;
use App\Http\Controllers\KnowledgeDocumentController;
use App\Http\Controllers\LocalCallScheduleController;
use App\Http\Controllers\ExotelController;
use App\Http\Controllers\ReportingAgentController;
use App\Http\Middleware\AuthenticateAdmin;
use Illuminate\Support\Facades\Route;

Route::post('/admin/login', [AdminAuthController::class, 'login'])->middleware('throttle:5,1');
Route::get('/admin/branding', [SettingsController::class, 'branding']);
Route::post('/exotel/status', [ExotelController::class, 'callback']);
Route::get('/exotel/internal/calls/{call}', [ExotelController::class, 'context']);
Route::post('/exotel/internal/calls/{call}/messages', [ExotelController::class, 'transcript']);
Route::post('/exotel/internal/calls/{call}/knowledge-search', [ExotelController::class, 'knowledgeSearch']);
Route::middleware(AuthenticateAdmin::class)->group(function () {
    Route::post('/exotel/calls', [ExotelController::class, 'start']);
    Route::get('/admin/me', [AdminAuthController::class, 'me']);
    Route::post('/admin/logout', [AdminAuthController::class, 'logout']);
    Route::get('/admin/settings', [SettingsController::class, 'show']);
    Route::put('/admin/settings', [SettingsController::class, 'update']);
    Route::put('/admin/account', [SettingsController::class, 'account'])->middleware('throttle:5,1');
    Route::get('/leads', [LeadController::class, 'index']);
    Route::post('/leads', [LeadController::class, 'store']);
    Route::get('/contacts', [ContactController::class, 'index']);
    Route::get('/local-call-schedules', [LocalCallScheduleController::class, 'index']);
    Route::post('/local-call-schedules', [LocalCallScheduleController::class, 'store']);
    Route::get('/local-call-schedules/{schedule}', [LocalCallScheduleController::class, 'show']);
    Route::post('/local-call-schedules/{schedule}/items/{item}/skip', [LocalCallScheduleController::class, 'skip']);
    Route::post('/local-call-schedules/{schedule}/items/{item}/retry', [LocalCallScheduleController::class, 'retry']);
    Route::post('/local-call-schedules/{schedule}/cancel', [LocalCallScheduleController::class, 'cancel']);
    Route::post('/contacts', [ContactController::class, 'store']);
    Route::get('/contacts/{contact}', [ContactController::class, 'show']);
    Route::put('/contacts/{contact}', [ContactController::class, 'update']);
    Route::get('/ai-agents', [AiAgentController::class, 'index']);
    Route::get('/reporting-agent', [ReportingAgentController::class, 'answer']);
    Route::post('/ai-agents', [AiAgentController::class, 'store']);
    Route::put('/ai-agents/{agent}', [AiAgentController::class, 'update']);
    Route::get('/knowledge-documents', [KnowledgeDocumentController::class, 'index']);
    Route::post('/knowledge-documents', [KnowledgeDocumentController::class, 'store']);
    Route::post('/knowledge-documents/search', [KnowledgeDocumentController::class, 'search']);
    Route::post('/knowledge-documents/{document}/replace', [KnowledgeDocumentController::class, 'replace']);
    Route::delete('/knowledge-documents/{document}', [KnowledgeDocumentController::class, 'destroy']);
    Route::get('/call-records', [CallRecordController::class, 'index']);
    Route::get('/call-records/{call}', [CallRecordController::class, 'show']);
    Route::get('/call-records/{call}/audio', [CallRecordController::class, 'audio']);
    Route::post('/call-records', [CallRecordController::class, 'store']);
    Route::post('/call-records/{call}/messages', [CallRecordController::class, 'storeMessage']);
    Route::post('/call-records/{call}/audio', [CallRecordController::class, 'uploadAudio']);
    Route::patch('/call-records/{call}', [CallRecordController::class, 'update']);
    Route::get('/schedule-events', [ScheduleEventController::class, 'index']);
    Route::post('/schedule-events', [ScheduleEventController::class, 'store']);
    Route::get('/schedule-events/{event}', [ScheduleEventController::class, 'show']);
    Route::patch('/schedule-events/{event}', [ScheduleEventController::class, 'update']);
    Route::post('/schedule-events/{event}/reschedule', [ScheduleEventController::class, 'reschedule']);
    Route::post('/schedule-events/{event}/cancel', [ScheduleEventController::class, 'cancel']);
    Route::post('/schedule-events/{event}/complete', [ScheduleEventController::class, 'complete']);
    Route::post('/call-records/{call}/schedule-events', [ScheduleEventController::class, 'store']);
});
